### ISSUE TITLE
Route confusion for default calendar year view

### ISSUE THREAD

**Issue by kabel** [unl/UNL_UCBCN_System#34]
https://github.com/unl/UNL_UCBCN_System/commit/b7d058f4ce44f33634fceb5915553c55d75a8b94#diff-f0a0c091e3f80158342e20aa65b92e14R10 introduced an issue with routing to the default calendar year view. I believe the original regular expression required a calendar short name to start with a letter to avoid year-like names. If you'd like to keep the ability for calendars to have shortn ames that start with a number, you'll probably want to move the shortcut Day route lower in the route array to allow the year prefixed routes to match first.

Problem URL: http://events.unl.edu/2015/ is routed to the day view of the "2015" calendar, rather than the year view for the default calendar.

**Comment by tlemburg** [comment]
Issue resolved. Feel free to make pull requests on these as well if you see an easy fix for them :)

**Comment by kabel** [comment]
Will do, just wanted to make sure the intention was to support short names that started with a number.
